/**
 * Serializes the edited content back into the two data-file modules and
 * downloads them. Drop the files into src/data/ and redeploy to publish.
 */
const js = (value) => JSON.stringify(value, null, 2)

function download(filename, text) {
  const a = document.createElement('a')
  a.href = URL.createObjectURL(new Blob([text], { type: 'text/javascript' }))
  a.download = filename
  a.click()
  URL.revokeObjectURL(a.href)
}

export function exportContent(content) {
  const header = (name) =>
    `/** ${name} — generated by the in-site editor on ${new Date().toISOString().slice(0, 10)}. */\n\n`

  download('projects.js', `${header('Projects')}export const projects = ${js(content.projects)}\n`)

  const site = ['hero', 'about', 'contact', 'links', 'skills', 'experience']
    .map((key) => `export const ${key} = ${js(content[key])}`)
    .join('\n\n')
  download('site.js', `${header('Site content')}${site}\n`)
}
